[package]
name = "cranelift-tools"
authors = ["The Cranelift Project Developers"]
version = "0.73.0"
description = "Binaries for testing the Cranelift libraries"
license = "Apache-2.0 WITH LLVM-exception"
documentation = "https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/docs/index.md"
repository = "https://github.com/bytecodealliance/wasmtime"
publish = false
edition = "2018"

[[bin]]
name = "clif-util"
path = "src/clif-util.rs"

[dependencies]
cfg-if = "1.0"
cranelift-codegen = { path = "codegen" }
cranelift-entity = { path = "entity" }
cranelift-interpreter = { path = "interpreter" }
cranelift-reader = { path = "reader" }
cranelift-frontend = { path = "frontend" }
cranelift-serde = { path = "serde", optional = true }
cranelift-wasm = { path = "wasm", optional = true }
cranelift-native = { path = "native" }
cranelift-filetests = { path = "filetests" }
cranelift-module = { path = "module" }
cranelift-object = { path = "object" }
cranelift-jit = { path = "jit" }
cranelift-preopt = { path = "preopt" }
cranelift = { path = "umbrella" }
cranelift-fuzzgen = { path = "fuzzgen" }
filecheck = "0.5.0"
log = "0.4.8"
termcolor = "1.1.2"
capstone = { version = "0.9.0", optional = true }
wat = { version = "1.0.36", optional = true }
target-lexicon = { version = "0.12", features = ["std"] }
peepmatic-souper = { path = "./peepmatic/crates/souper", optional = true }
pretty_env_logger = "0.4.0"
rayon = { version = "1", optional = true }
file-per-thread-logger = "0.1.2"
indicatif = "0.13.0"
thiserror = "1.0.15"
walkdir = "2.2"
anyhow = "1.0.32"
structopt = "0.3.17"

[features]
default = ["disas", "wasm", "cranelift-codegen/all-arch", "peepmatic-souper", "souper-harvest"]
disas = ["capstone"]
enable-peepmatic = ["cranelift-codegen/enable-peepmatic", "cranelift-filetests/enable-peepmatic"]
wasm = ["wat", "cranelift-wasm"]
experimental_arm32 = ["cranelift-codegen/arm32", "cranelift-filetests/experimental_arm32"]
souper-harvest = ["cranelift-codegen/souper-harvest", "rayon"]
all-arch = ["cranelift-codegen/all-arch"]
