freebsd_instance:
  image_family: freebsd-13-0
  
task:
  env:
    PATH: $PATH:$HOME/.cargo/bin
  install_script: 
    - pkg install -y curl
    - pkg install -y git-tiny gohugo
    - git submodule init
    - git submodule update
  script: 
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - cargo build --release
