freebsd_instance:
  image_family: freebsd-13-0
  
task:
  install_script: pkg install -y curl
  script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
task:
  install_script: rustup install stable
  script: cargo build --release
