freebsd_instance:
  image_family: freebsd-13-0
  
task:
  env:
    PATH: $PATH:$HOME/.cargo/bin
  submodules_script:
    - git submodule init
    - git submodule update
  install_script: pkg install -y curl
  script: 
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - cargo build --release
