[package]
name = "wasmtime-wasi-nn"
version.workspace = true
authors.workspace = true
description = "Wasmtime implementation of the wasi-nn API"
documentation = "https://docs.rs/wasmtime-wasi-nn"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "computer-vision"]
keywords = ["webassembly", "wasm", "neural-network"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[dependencies]
# These dependencies are necessary for the witx-generation macros to work:
anyhow = { workspace = true }
wiggle = { workspace = true }

# These dependencies are necessary for the wasi-nn implementation:
# TODO: update tensorflow once a new version has been released with the needed changes on crates.io.
tensorflow = { git = "https://github.com/brianjjones/rust.git", rev = "e79d43", default-features = false, features = ["tensorflow_runtime_linking"]}
openvino = { version = "0.4.2", features = ["runtime-linking"] }
thiserror = { workspace = true }

[build-dependencies]
walkdir = "2.3"

[badges]
maintenance = { status = "experimental" }

[dev-dependencies]
tempfile = "3"
