[package]
name = "wasmtime-wasi-nn"
version.workspace = true
authors.workspace = true
description = "Wasmtime implementation of the wasi-nn API"
documentation = "https://docs.rs/wasmtime-wasi-nn"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "computer-vision"]
keywords = ["webassembly", "wasm", "neural-network"]
repository = "https://github.com/bytecodealliance/wasmtime"
readme = "README.md"
edition.workspace = true

[dependencies]
# These dependencies are necessary for the WITX-generation macros to work:
anyhow = { workspace = true }
wiggle = { workspace = true }
wit-bindgen = { workspace = true }
wit-component = { workspace = true }
wasmtime-wasi = { workspace = true, features = ["tokio"] }
# This dependency is necessary for the WIT-generation macros to work:
wasmtime = { workspace = true, features = ["component-model"] }

# These dependencies are necessary for the wasi-nn implementation:
tracing = { workspace = true }
openvino = { version = "0.5.0", features = ["runtime-linking"] }
thiserror = { workspace = true }
hyper = { version = "=1.0.0-rc.3", features = ["full"] }
http-body-util = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "1.8.0", features = ["rt", "time", "macros", "rt-multi-thread", "net"] }
byteorder = "1.4.3"

[build-dependencies]
walkdir = { workspace = true }
