[package]
name = "winch-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmparser = { workspace = true }
smallvec = { workspace = true }
anyhow = { workspace = true }
target-lexicon = { workspace = true, features = ["std"] }
cranelift-codegen = { workspace = true }
# Interim dependency; mostly to have access to `PReg`s.
# In the long term, we'll factor out the register
# abstractions from regalloc2 for them to be consumed
# from Winch and Cranelift.
regalloc2 = "0.4.1"

[features]
x64 = ["cranelift-codegen/x86"]
arm64 = ["cranelift-codegen/arm64"]
all-arch = [
    "x64",
    "arm64",
]
