[package]
name = "wasmtime-winch"
edition = "2021"
description = "Integration between Wasmtime and Winch"
version.workspace = true

[dependencies]
winch-codegen = { workspace = true }
target-lexicon = { workspace = true }
wasmtime-environ = { workspace = true }
anyhow = { workspace = true }

[features]
default = ["all-arch", "component-model"]
component-model = ["wasmtime-environ/component-model"]
all-arch = ["winch-codegen/all-arch"]
