name: 'Free Disk Space'
description: 'Deletes unneccesary packages to save disk space, sourced partially from https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh'

runs:
  using: composite
  steps:
    - run: ${GITHUB_ACTION_PATH//\\//}/main_linux.sh
      if: runner.os == 'Linux'
      shell: bash
    - run: ${{ github.action_path }}/main_windows.bat
      if: runner.os == 'Windows'
      shell: cmd
