name: CI
on:
  push:
    branches: [main]
    tags-ignore: [dev]
    paths-ignore:
      - 'meetings/**'
  pull_request:
    branches: ['main', 'release-*']
    paths-ignore:
      - 'meetings/**'
defaults:
  run:
    shell: bash

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      QEMU_BUILD_VERSION: 6.1.0
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
          - os: windows-2022
            target: x86_64-pc-windows-gnu
          - os: windows-2019
          - os: windows-2019
            target: x86_64-pc-windows-gnu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ./.github/actions/install-rust

    # Install targets in order to build various tests throughout the repo
    - run: rustup target add wasm32-wasi wasm32-unknown-unknown ${{ matrix.target }}

    - run: cargo test --test all -- wast::Cranelift::misc::stack_overflow --nocapture
      env:
        RUST_BACKTRACE: 1
